// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahyxslcntwjkmifzhwng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeXhzbGNudHdqa21pZnpod25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzMjg1ODksImV4cCI6MjA5NTkwNDU4OX0.qXORrgCngDYliWbBT6llbBChsTHQq9dBnNhl5925j8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);